### ISSUE TITLE
Sync color change on hover of Home disc/button

### ISSUE THREAD

**Issue by ritot** [WilliamsUltimate/williamsultimate#1]
Currently, when hovering over a team disc or button on the Home page, the color turns from white to light purple.

It would be nice to sync them (i.e. if you hover over the disc, the button also changes color and vice versa) so users can more easily make the connection between logo and team name, as well as the fact that the discs are clickable.

Look into: https://stackoverflow.com/questions/48047940/how-to-change-the-style-of-one-element-when-i-hover-another-element-reactjs

**Comment by alansun25** [comment]
@ritot This will be a little different now that we're changing the navbar

**Comment by ritot** [comment]
Yup, closing this issue because of PR #24
