### ISSUE TITLE
Add analytics so that you can monitor the websites traffic

### ISSUE THREAD

**Issue by kaizen3031593** [WilliamsUltimate/williamsultimate#12]
You should almost certainly be using Google Analytics. I can help, but it is also a fun and relevant journey to figure this out on your own. But in the end you get fun statistics on how many people are using your website. 

For example, if you find out that 100% of people are using your website via desktop, maybe mobile friendly is not a priority. Although that's almost certainly not the case...

If you have already done this, then cool. Feel free to close.

**Comment by alansun25** [comment]
[https://javascript.plainenglish.io/how-to-setup-and-add-google-analytics-to-your-react-app-fd361f47ac7b](url)

**Comment by kaizen3031593** [comment]
Not long term bro! This is something that should get shipped with the initial website. Very important for you own resumes to say “website with XXX visitors a month”

**Comment by ritot** [comment]
Okay lemme get on it
