### ISSUE TITLE
Change the team navbar logo on hover

### ISSUE THREAD

**Issue by ritot** [WilliamsUltimate/williamsultimate#25]
If you're on the WUFO page for example, there's a WUFO logo in the top left. Clicking on it brings you back to the main homepage, which might be a little confusing? Some people might think it's meant to go to the top of the team page.

Instead, on hover we can have it flip to a WUF logo (gotta make one first), home icon, or something else.

Just a thought, might just end up keeping the team logo in the end.

**Comment by alansun25** [comment]
Oh true. Maybe we can use the react card flip component for this so on hover it looks like the current team logo flips into the org-wide logo.

**Comment by ritot** [comment]
> Oh true. Maybe we can use the react card flip component for this so on hover it looks like the current team logo flips into the org-wide logo.

Yeah that's exactly how I came up with the idea! Just gotta find/make a suitable logo 🤔
